version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  test:
    docker:
      - image: morevi/jobcontrol
 
    steps:
      - checkout
      - run:
          name: Run tests
          command: docker run -t -v `pwd`:/app/test morevi/jobcontrol

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test
