name: "DockerHub"

on:
  push:
    paths:
      # only if these files had changes
      - Dockerfile
      - pyproject.toml
      - poetry.lock

jobs:
  buildnpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: morevi/jobcontrol:latest

      - name: Sync readme
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_PASSWORD }}
          description: true 
