name: "Run tests on docker"

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: docker run -t -v `pwd`:/app/test morevi/jobcontrol
